import { useMemo, useState } from 'react'
import { ArrowRight, Check, Clock3, MapPin, Menu, Minus, Phone, Plus, ShoppingBag, X } from 'lucide-react'
import { CoverFlowCarousel } from './components/ui/3-d-coverflow-carousel'
import './App.css'

type Category = 'All' | 'Coffee' | 'Tea' | 'Milkshakes' | 'Burgers' | 'Pizza' | 'Snacks' | 'Desserts'
type Product = { id: number; name: string; category: Exclude<Category, 'All'>; description: string; price: number; image: string; badge?: string }
const products: Product[] = [
  { id: 1, name: 'Carton Cloud Latte', category: 'Coffee', description: 'Honey foam, double espresso, silky oat milk', price: 7.5, image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=900&q=85', badge: 'Best seller' },
  { id: 2, name: 'Strawberry Pop Shake', category: 'Milkshakes', description: 'Berry whip, vanilla cream, candy crunch', price: 8.9, image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=900&q=85', badge: 'New' },
  { id: 3, name: 'Golden Crunch Burger', category: 'Burgers', description: 'Crispy chicken, cheddar, house carton sauce', price: 13.5, image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85' },
  { id: 4, name: 'Hot Honey Slice', category: 'Pizza', description: 'Fior di latte, pepperoni, hot honey drizzle', price: 11.9, image: 'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=900&q=85' },
  { id: 5, name: 'Cloudberry Cheesecake', category: 'Desserts', description: 'Baked vanilla cheesecake, berry compote', price: 8.2, image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=900&q=85' },
  { id: 6, name: 'Chili Cheese Bites', category: 'Snacks', description: 'Golden potato bites, jalapeño cheese dip', price: 6.5, image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=85' },
  { id: 7, name: 'Peach Oolong Fizz', category: 'Tea', description: 'Cold-brew oolong, peach, citrus sparkle', price: 6.9, image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=85' },
]
const categories: Category[] = ['All', 'Coffee', 'Tea', 'Milkshakes', 'Burgers', 'Pizza', 'Snacks', 'Desserts']

function App() {
  const [category, setCategory] = useState<Category>('All')
  const [cart, setCart] = useState<number[]>([])
  const [cartOpen, setCartOpen] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const visibleProducts = useMemo(() => category === 'All' ? products : products.filter((item) => item.category === category), [category])
  const cartProducts = cart.map((id) => products.find((item) => item.id === id)).filter(Boolean) as Product[]
  const cartTotal = cartProducts.reduce((sum, item) => sum + item.price, 0)
  const addToCart = (id: number) => setCart((current) => [...current, id])
  const removeFromCart = (id: number) => setCart((current) => { const index = current.indexOf(id); return index < 0 ? current : [...current.slice(0, index), ...current.slice(index + 1)] })
  const closeMenu = () => setMenuOpen(false)

  return <div className="app-shell">
    <div className="topline"><span>Free delivery on orders over $35</span><span>Open daily · 7am — 10pm</span><span className="topline-social">@pikachucarton</span></div>
    <header className="site-header"><a className="brand" href="#top"><span className="brand-mark">PC</span><span>PIKACHU<br /><em>CARTON</em></span></a><nav className={menuOpen ? 'main-nav mobile-visible' : 'main-nav'}><a href="#menu" onClick={closeMenu}>Menu</a><a href="#story" onClick={closeMenu}>Our story</a><a href="#reviews" onClick={closeMenu}>Reviews</a><a href="#visit" onClick={closeMenu}>Find us</a></nav><div className="header-actions"><a className="order-link" href="#menu">Order online <ArrowRight size={15} /></a><button className="cart-button" onClick={() => setCartOpen(true)} aria-label="Open cart"><ShoppingBag size={19} /><span>{cart.length}</span></button><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></div></header>
    <main id="top">
      <section className="hero-section"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line" /> GOOD MOOD FOOD <span className="eyebrow-line" /></div><h1>Welcome to<br /><span>Pikachu</span> Carton</h1><p>A bright little café for big cravings, tiny celebrations, and everything in between.</p><div className="hero-actions"><a className="button button-dark" href="#menu">Explore the menu <ArrowRight size={17} /></a><a className="text-link" href="#story">Meet the mascot <span>↗</span></a></div><div className="hero-note"><div className="avatar-stack"><span>J</span><span>M</span><span>A</span></div><span><strong>4.9/5</strong> from 2,000+ happy sips</span></div></div><div className="hero-art"><div className="sun-disc" /><div className="star star-one">✦</div><div className="star star-two">✦</div><div className="burst">✳</div><div className="mascot"><div className="ear ear-left" /><div className="ear ear-right" /><div className="mascot-body"><div className="mascot-eye eye-left" /><div className="mascot-eye eye-right" /><div className="mascot-cheek cheek-left" /><div className="mascot-cheek cheek-right" /><div className="mascot-mouth" /><div className="mascot-arm arm-left" /><div className="mascot-arm arm-right" /></div><div className="mascot-feet"><span /><span /></div></div><div className="hero-food food-cup"><div className="cup-lid" /><div className="cup-face">•ᴗ•</div></div><div className="hero-food food-donut">🍩</div><div className="hero-label">HAPPY<br /><strong>INSIDE</strong></div></div></section>
      <section className="ticker"><div>✦ HANDCRAFTED DAILY</div><div>✦ ZERO BORING BITES</div><div>✦ EXTRA HAPPY ENERGY</div><div>✦ HANDCRAFTED DAILY</div></section>
      <section className="feature-section"><div className="section-kicker">THE CARTON FAVES</div><div className="feature-heading"><h2>Good things<br /><i>come in cartons.</i></h2><p>Our cult favourites are made fresh, served fun, and designed to make your day a little more delicious.</p><a className="circle-arrow" href="#menu" aria-label="Explore the menu"><ArrowRight size={22} /></a></div><CoverFlowCarousel /></section>
      <section className="menu-section" id="menu"><div className="menu-intro"><div><div className="section-kicker">ORDER ONLINE</div><h2>Pick your<br /><i>happy.</i></h2></div><p>From first sip to last crumb, there is a little joy in every box. Tap, add, repeat.</p></div><div className="category-tabs" role="tablist">{categories.map((item) => <button key={item} className={item === category ? 'active' : ''} onClick={() => setCategory(item)}>{item}</button>)}</div><div className="product-grid">{visibleProducts.map((product) => <article className="product-card" key={product.id}><div className="product-image">{product.badge && <span className="product-badge">{product.badge}</span>}<img src={product.image} alt={product.name} /><button className="quick-add" onClick={() => addToCart(product.id)} aria-label={`Add ${product.name} to cart`}><Plus size={20} /></button></div><div className="product-info"><div><span className="product-category">{product.category}</span><h3>{product.name}</h3><p>{product.description}</p></div><strong>${product.price.toFixed(2)}</strong></div></article>)}</div></section>
      <section className="offer-section"><div className="offer-copy"><div className="section-kicker">THE CARTON CLUB</div><h2>Sweet deal,<br /><i>even sweeter.</i></h2><p>Get any drink + snack combo for just $12. Every weekday from 2—5pm. That is what we call a very good break.</p><a className="button button-yellow" href="#menu">Claim the deal <ArrowRight size={17} /></a></div><div className="offer-visual"><div className="offer-badge">$12<br /><small>COMBO</small></div><div className="offer-shape shape-cup">☕</div><div className="offer-shape shape-cookie">✦</div><div className="offer-sticker">BREAK<br />TIME!</div></div></section>
      <section className="story-section" id="story"><div className="story-image"><img src="https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=1200&q=85" alt="Warm Pikachu Carton cafe interior" /><span className="image-tag">EST. 2021 / BROOKLYN</span></div><div className="story-copy"><div className="section-kicker">A LITTLE ABOUT US</div><h2>Made for<br /><i>the main character.</i></h2><p>We built Pikachu Carton for the days that deserve a little more colour. A place to meet your people, fuel your ideas, and turn an ordinary Tuesday into a tiny celebration.</p><div className="story-stats"><div><strong>7</strong><span>daily bakes</span></div><div><strong>16</strong><span>happy sauces</span></div><div><strong>∞</strong><span>good vibes</span></div></div><a className="text-link" href="#visit">Read our story <span>↗</span></a></div></section>
      <section className="reviews-section" id="reviews"><div className="reviews-heading"><div className="section-kicker">LOVE NOTES</div><h2>Do not just<br /><i>take our word.</i></h2><div className="review-arrows"><button aria-label="Previous review">←</button><button aria-label="Next review">→</button></div></div><div className="review-card"><div className="stars">★★★★★</div><blockquote>“The kind of place that makes you want to cancel your plans and stay for one more slice. The cloud latte is genuinely life changing.”</blockquote><div className="review-person"><div className="review-avatar">LS</div><div><strong>Leah Stone</strong><span>Regular & professional joy seeker</span></div></div></div></section>
      <section className="visit-section" id="visit"><div><div className="section-kicker">COME SAY HI</div><h2>Your new<br /><i>happy place.</i></h2></div><div className="visit-details"><div><MapPin size={19} /><span><strong>48 Carton Street</strong>Brooklyn, NY 11211</span></div><div><Clock3 size={19} /><span><strong>Open every day</strong>7am — 10pm</span></div><div><Phone size={19} /><span><strong>Say hello</strong>(718) 555-CARTON</span></div></div><a className="button button-dark" href="mailto:hello@pikachucarton.com">Plan a visit <ArrowRight size={17} /></a></section>
    </main>
    <footer><a className="brand" href="#top"><span className="brand-mark">PC</span><span>PIKACHU<br /><em>CARTON</em></span></a><span>© 2024 Pikachu Carton. Made with extra cheese.</span><div><a href="#top">Instagram</a><a href="#top">TikTok</a><a href="#top">Contact</a></div></footer>
    {cartOpen && <div className="cart-overlay" onClick={() => setCartOpen(false)}><aside className="cart-drawer" onClick={(event) => event.stopPropagation()}><div className="cart-header"><div><span className="section-kicker">YOUR ORDER</span><h2>Good choice.</h2></div><button onClick={() => setCartOpen(false)} aria-label="Close cart"><X size={21} /></button></div>{cartProducts.length === 0 ? <div className="empty-cart"><ShoppingBag size={35} /><p>Your carton is empty.<br />Let us fix that.</p><a className="button button-dark" href="#menu" onClick={() => setCartOpen(false)}>Browse menu</a></div> : <><div className="cart-items">{cartProducts.map((product, index) => <div className="cart-item" key={`${product.id}-${index}`}><img src={product.image} alt="" /><div><strong>{product.name}</strong><span>${product.price.toFixed(2)}</span><div className="quantity"><button onClick={() => removeFromCart(product.id)}><Minus size={13} /></button><span>1</span><button onClick={() => addToCart(product.id)}><Plus size={13} /></button></div></div></div>)}</div><div className="cart-summary"><div><span>Subtotal</span><strong>${cartTotal.toFixed(2)}</strong></div><div><span>Delivery</span><strong>Free</strong></div><div className="cart-total"><span>Total</span><strong>${cartTotal.toFixed(2)}</strong></div><button className="button button-dark checkout-button"><Check size={17} /> Checkout</button></div></>}</aside></div>}
  </div>
}

export default App
